version: '3.4'

services:
  postgres_user:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_db
    ports:
      - '6001:5432'
    volumes:
      - ./postgres/user:/var/lib/postgresql/data # restart를 해도 데이터가 남아있도록 하기 위해서
    healthcheck: # 서버가 실행이 될 때
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
  user:
    build:
      context: .
      dockerfile: ./apps/user/Dockerfile
      target: development # 왜 사용할수 없는지?
    command: npm run start:dev user
    depends_on:
      postgres_user: # postgres_db에 의존
        condition: service_healthy # db가 건강할 때 만
    ports:
      - '3001:3000' # 3001: 현재 내 로컬, 3000은 docker내의 포트
    volumes:
      - .:/usr/src/app # 원하는 위치 동기화 -> 자동으로 재시작이 불가
      - /usr/src/app/node_modules # node_modules는 동기화 하지 않음

